#####################################################################
#
# This is written by Zhiyang Ong 
# for EE577b Extra Credit Homework #2
#
#####################################################################


# Test case 5
# Synthesize the encoder and the decoder
syn:
	@echo == Synthesize the encoder
	dc_shell-t -f ./script/encoder.tcl
	@echo == Synthesize the decoder
	dc_shell-t -f ./script/decoder.tcl
